name: Create S3 Bucket using CloudFormation

on:
  push:
    branches:
      - main

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Create S3 Bucket using CloudFormation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudformation create-stack --stack-name my-s3-stack --template-body file://path/to/s3-bucket-template.yaml --capabilities CAPABILITY_IAM
